// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQXtwUo_ywFx8cuIIM8k2erwlMa7YzfX0',
    appId: '1:562175325371:web:208f402856fda9a9c6659e',
    messagingSenderId: '562175325371',
    projectId: 'travel-buddies-52d80',
    authDomain: 'travel-buddies-52d80.firebaseapp.com',
    storageBucket: 'travel-buddies-52d80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTNxh9zRR9CVI90K3qcZkGMR2v3V8otlc',
    appId: '1:562175325371:android:56eb9e8040cfa541c6659e',
    messagingSenderId: '562175325371',
    projectId: 'travel-buddies-52d80',
    storageBucket: 'travel-buddies-52d80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeV_O6FK9CIG2xk_4BREOxhOKF13iyCrU',
    appId: '1:562175325371:ios:50d3559f4450b306c6659e',
    messagingSenderId: '562175325371',
    projectId: 'travel-buddies-52d80',
    storageBucket: 'travel-buddies-52d80.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeV_O6FK9CIG2xk_4BREOxhOKF13iyCrU',
    appId: '1:562175325371:ios:50d3559f4450b306c6659e',
    messagingSenderId: '562175325371',
    projectId: 'travel-buddies-52d80',
    storageBucket: 'travel-buddies-52d80.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQXtwUo_ywFx8cuIIM8k2erwlMa7YzfX0',
    appId: '1:562175325371:web:897f9374321de63bc6659e',
    messagingSenderId: '562175325371',
    projectId: 'travel-buddies-52d80',
    authDomain: 'travel-buddies-52d80.firebaseapp.com',
    storageBucket: 'travel-buddies-52d80.firebasestorage.app',
  );
}
